// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fytjdsmnsbzzrytewjqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5dGpkc21uc2J6enJ5dGV3anFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDE0OTcsImV4cCI6MjA2MTExNzQ5N30.A-5FzkaXDpeSzjEyY7XDCmCKxdgO-PNm4uPkLJZ5pVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});